local sensitive_list = {
    ["data_key"] = "brianyummy",
    ["max_purchase_id_cache_size"] = 100, 
    ["daily_deal_reset_hour"] = 0, -- UTC TIME
    ["developers"] = {
        315611317, -- Brian Main (SaberOscar)
        2354566520, -- Brian Deving (CriticalCyanide)
        143320560, -- Daniel Main (VoidedLiqht)
        5010740015, -- Daniel Deving (CxrescentMoon)
    },
}

return sensitive_list